# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.11'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}'
        install-deps: 'true'
        modules: ''
        cached: 'false'
        setup-python: 'true'
        tools: 'tools_ifw,4.1.1,qt.tools.ifw.41 tools_qtcreator,5.0.2-0,qt.tools.qtcreator'
        set-env: 'false'
        tools-only: 'false'
        aqtversion: '==1.2.5'
        py7zrversion: '==0.16.1'
        extra: '--external 7z'
